<h2>Products</h2>
<h1>Swaddling Mama</h1>
                     <p>
                     A relaxation / imagery CD designed to reassure, nurture and empower mothers and to help them feel confident and strong in their role as a mother.
                     </p>
                     <p>
                    <img height="200" width="199" src="images/swaddlingmama.jpg" vspace="0" hspace="0" align="RIGHT" border="0" alt="Swaddling Mama" style="margin-left: 20px; margin-bottom: 20px;">
					 On this 75 minute CD you will find all the comfort and reassurance you need:
                     </p>
                     <ul>
                        <li><b>Loving Affirmations</b> - This track is designed to give you a boost where you need it most, your psyche. You can listen to this track anywhere you like, in the car, doing dishes, relaxing... Just listen and repeat these loving thoughts. </li>
                        <li><b>Quick and Easy Relaxation/Imagery</b> - You may not have a lot of time as a new mom, so this track is designed to help you relax quickly and easily. (10 minutes)</li>
                        <li><b>Long and Luxurious Relaxation/Imagery</b> - This track is for when you &#8220;surprisingly&#8221; can take a much needed and longer time to relax. (20 minutes) </li>
                        <li><b>Milk Flow</b> - This track is a helpful imagery exercise for new moms who are breast feeding or pumping and may not have an ample supply of milk. Or simply a way to relax and rest while feeding your baby.</li>
                        <li><b>Happy Nappy Time</b> - Fall asleep fast with this track that is designed for the new mom in mind. Use this to rest in the afternoon while your baby naps or to get back to sleep in the middle of the night.</li>
                       </ul>
                       <p><form action="https://www.paypal.com/cgi-bin/webscr" method="post">
$19.95&nbsp;
<input type="hidden" name="cmd" value="_s-xclick">
<input type="image" src="https://www.paypal.com/en_US/i/btn/x-click-but23.gif" border="0" name="submit" alt="Purchase Swaddling Mama">
<img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
<input type="hidden" name="encrypted" value="-----BEGIN PKCS7-----MIIHdwYJKoZIhvcNAQcEoIIHaDCCB2QCAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYAqKHU/ufBk8Dhn4ho7D8IFE6oQ39aKTSOisMMUfyv/tkXmVvaWWZd+EiDZ2WVXK+J1QEMwERvu2LQP69k0cSqOjXCZ8iXgKNvZcHrm9/YIUJtTmNRJWoS+2AVZuiFThbu8sUv1+nPZpvkjs2nrViulDYhxPOnQEu/GuoBWFdvqgTELMAkGBSsOAwIaBQAwgfQGCSqGSIb3DQEHATAUBggqhkiG9w0DBwQIDCUKtJrJB1mAgdAM60Rb7HG+OuCxOAUjwpyrrJ7JWdwfnKFNbmr4oH66eWJ2R+w8emWbO1Z+OafobBWNOVb6NBFnbtMmPpmbkAKn762qLLtBs/rG7QpNsIVT+wBLOfaJsqInUcWBOU+0H/aYHIPhuQvgorAmzDwe0h6hhaRbnE28WxenuZvGPUmTkFQY/6VIykOU58DktWy3qODZsFSjTH60WnOjgcEgqdYwN5yMEYuCVgo68RSgHinjZXuud8CEOufu3PGubFN+Yg1WcWaDj/XJqmtomD2lhi1hoIIDhzCCA4MwggLsoAMCAQICAQAwDQYJKoZIhvcNAQEFBQAwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tMB4XDTA0MDIxMzEwMTMxNVoXDTM1MDIxMzEwMTMxNVowgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDBR07d/ETMS1ycjtkpkvjXZe9k+6CieLuLsPumsJ7QC1odNz3sJiCbs2wC0nLE0uLGaEtXynIgRqIddYCHx88pb5HTXv4SZeuv0Rqq4+axW9PLAAATU8w04qqjaSXgbGLP3NmohqM6bV9kZZwZLR/klDaQGo1u9uDb9lr4Yn+rBQIDAQABo4HuMIHrMB0GA1UdDgQWBBSWn3y7xm8XvVk/UtcKG+wQ1mSUazCBuwYDVR0jBIGzMIGwgBSWn3y7xm8XvVk/UtcKG+wQ1mSUa6GBlKSBkTCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb22CAQAwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQUFAAOBgQCBXzpWmoBa5e9fo6ujionW1hUhPkOBakTr3YCDjbYfvJEiv/2P+IobhOGJr85+XHhN0v4gUkEDI8r2/rNk1m0GA8HKddvTjyGw/XqXa+LSTlDYkqI8OwR8GEYj4efEtcRpRYBxV8KxAW93YDWzFGvruKnnLbDAF6VR5w/cCMn5hzGCAZowggGWAgEBMIGUMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbQIBADAJBgUrDgMCGgUAoF0wGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMDcwODMwMDU0MjMyWjAjBgkqhkiG9w0BCQQxFgQUWrIsp/ASHS6WpR499kMR0g/Mku8wDQYJKoZIhvcNAQEBBQAEgYCgNydIblUE3rldjoli3mkKViWhyPb9IYC1fanv5RT4/ipbhiCdZz5NkyEoimBDABL0On+RErCHpZHOJNOcwbwnnLvkyI6mIQBbOnAdtobGhB3SKrS/AnxRE3Pcmc5VrKWeWXKWbZCalXoqryz7hCz+4ZSttu06cAmtf/114ENwjA==-----END PKCS7-----
">
</form></p>